[tool.poetry]
name = "qgis-plugin"
version = "0.0.0"
description = ""
authors = ["MIERUNE Inc. <no-reply@mierune.co.jp>"]
readme = "README.md"
packages = [{ include = "my_plugin" }]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
flake8-bugbear = "^23.2.13"
flake8-docstrings = "^1.7.0"
flake8 = "^6.0.0"
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.flake8]
select = "B,C,E,F,W,D,B950"
ignore = "E203,E501,W503"
extend-ignore = "B008,D415,D400,D104"
max-line-length = 88
docstring-convention = "google"
