[tool.poetry]
name = "qgis-mojxml-plugin"
version = "0.0.0"
description = "A QGIS plugin for converting Japanese “MOJ Map XML” (land registration polygons in Japan) into geospatial formats."
authors = ["MIERUNE Inc. <info@mierune.co.jp>"]
readme = "README.md"
packages = [{ include = "mojxml_plugin" }]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pyqt5-stubs = { version = "^5.15.6.0", platform = "win32" }
ruff = "^0.0.261"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = ["--import-mode=importlib"]

[tool.ruff]
select = ["F", "E", "W", "B", "C90", "N", "I"]
ignore = ["N802", "E501"]
target-version = "py38"

[tool.coverage.run]
source = ['mojxml_plugin']
omit = ['mojxml_plugin/mojxml/*']
concurrency = ["thread"]
