[tool.poetry]
name = "qgis-mojxml-plugin"
version = "0.0.0"
description = "QGISで法務省登記所備付地図データ（地図XML）の読み込みや変換を行うプラグイン"
authors = ["MIERUNE Inc. <info@mierune.co.jp>"]
readme = "README.md"
packages = [{ include = "mojxml_plugin" }]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"

[tool.poetry.group.dev.dependencies]
flake8-bugbear = "^23.3.12"
flake8 = "^6.0.0"
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.2"
flake8-pyproject = "^1.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
# pythonpath = "src"
addopts = ["--import-mode=importlib"]

[tool.flake8]
exclude = ".venv,.git,__pycache__"
extend-ignore = "E203,E501,W503,B008"
max-line-length = 88
docstring-convention = "google"
