name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  Release:
    name: Make zip package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip plugin package
        run: make package

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/artifact-HEAD.zip#${{ env.ASSET_NAME }}
