name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull QGIS
        run: docker pull qgis/qgis:latest

      - name: Export requirements.txt
        run: |
          pip3 install poetry
          poetry export --with dev -f requirements.txt -o requirements.txt

      - name: Run tests
        run: >
          docker run --rm --volume `pwd`:/app -w=/app qgis/qgis:latest sh -c
          "pip3 install -r requirements.txt && pip3 install 'shapely<2.0' && PYTHONPATH=/app xvfb-run -s '+extension GLX -screen 0 1024x768x24'
          pytest -v --cov --cov-report=xml --cov-report=term"

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
